### ISSUE TITLE
Crash when using project build with version 0.2.3

### ISSUE THREAD

**Issue by simonseyer** [jensmeder/Phoenx#22]
When executing `phoenx project build` with version `0.2.3` the generation crashes with the following stacktrace. `phoenx workspace build` works flawlessly as well `phoenx project build` when using version `0.2.2`.

Would be nice if you could have a look.

Cheers :-)

```
NoMethodError: undefined method `find_file_by_path' for nil:NilClass
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/use_cases/generate_project.rb:84:in `block in add_config_files'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/use_cases/generate_project.rb:76:in `each'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/use_cases/generate_project.rb:76:in `add_config_files'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/use_cases/generate_project.rb:27:in `build'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/cli_factory.rb:106:in `block in project_command'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:47:in `call'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:47:in `parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:59:in `block (2 levels) in parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:53:in `each'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:53:in `block in parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:51:in `each'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:51:in `parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:59:in `block (2 levels) in parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:53:in `each'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:53:in `block in parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:51:in `each'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/lib/phoenx/cli/command.rb:51:in `parse'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/gems/phoenx-0.2.3/bin/phoenx:9:in `<top (required)>'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/bin/phoenx:23:in `load'
  /Users/simon/Development/COBI/iOS/COBIUtils/vendor/bundle/ruby/2.0.0/bin/phoenx:23:in `<top (required)>'
```

**Comment by simonseyer** [comment]
Got fixed with #23
